version: v2

replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: Never

service:
  create: false
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 1
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi

livenessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 5

readinessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 5

env:
  enableFeatureX: true
