apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: booking-service
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: booking-service
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: booking-service
        version: {{ .Values.version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: ENABLE_FEATURE_X
              value: "{{ .Values.env.enableFeatureX }}"
            - name: SERVICE_VERSION
              value: "{{ .Values.version }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
