{{- if .Values.service.create }} #деплоим оба v1,v2 но создается один раз, так как для v2 .Values.service.create == false
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: booking-service
{{- end }}
